[package]
name = "rgz_transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rgz_msgs = { path = "../rgz_msgs" }
prost = "0.11.9"
prost-types = "0.11.9"

